import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
// import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
// import { AppSidebar } from "./admin/components/app-side-bar/AppSideBar";


const OutrequeRegular = localFont({
  src: "../../public/fonts/OutrequeRegular.ttf",
  display: "swap",
  variable: "--font-outreque-regular",
});
const NewYorkRegular = localFont({
  src: "../../public/fonts/NewYork.otf",
  display: "swap",
  variable: "--font-newyork-regular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${OutrequeRegular.variable} ${NewYorkRegular.variable} antialiased`}>
        {children}
      </body>
    </html>
  );

  
}


